server:
  listen: 8080
  workers : 4
  upstreams:
    - id: node1
      url: http://localhost:8001
    - id: node2
      url: http://localhost:8002
    - id: node3
      url: http://localhost:8003
    - id: node4
      url: http://localhost:8004
  headers:
    - key: x-forward-for
      value: "$ip"
    - key: Authorization
      value: "Bearer qwerty"
  rules:
    - path: /
      upstreams:
        - node1
        - node2
    - path: /admin
      upstreams:
        - node3
