server:
  listen: 8080
  workers: 4
  upstreams:
    - id: node1
      url: jsonplaceholder.typicode.com
    - id: node2
      url: jsonplaceholder.typicode.com
    - id: node3
      url: jsonplaceholder.typicode.com
    - id: node4
      url: jsonplaceholder.typicode.com
  headers:
    - key: x-forward-for
      value: "$ip"
    - key: Authorization
      value: "Bearer qwerty"
  rules:
    - path: /comments
      upstreams:
        - node3
    - path: /todos
      upstreams:
        - node3
    - path: /
      upstreams:
        - node1
        - node2
